name: discord_interaction_to_pubsub
description: A microservice that turns Discord Interactions into PubSub messages.
version: 0.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  shelf: ^1.2.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  http: ^0.13.4